### ISSUE TITLE
環境構築とサンプルボタンの実装

### ISSUE THREAD

**Issue by molpui0726** [YKhm20020/Frontend-Festival-Booth#1]
決めるべき技術

- 言語・フレームワーク
- CSS
- ランタイム
- ツール

バックエンドについては別リポジトリを参照。
https://github.com/aridome222/Backend-Festival-Booth

**Comment by molpui0726** [comment]
ランタイム: Node.js

Denoが候補に。
今回は参加者の半数がフロントエンドを初めて触るため、安定しているNode.jsを採用。

**Comment by molpui0726** [comment]
言語・フレームワーク: React

Next.js が候補に。
まずは Reactを学んでから Next.js に進みたい意見から、Reactを採用。

**Comment by molpui0726** [comment]
ツール: Storybook, Biome

スモークテストのため、Storybookを採用。VRT、インタラクションテストについては、時間があったら順次書いていく。
Biomeは高速に動作する、かつ標準で備えている機能が多い（ESLintだと外部プラグインが必要なものがBiomeだと標準でサポートされており、configファイルで設定できる）ため、採用。

**Comment by aridome222** [comment]
CSS ：tailwindcss

理由：今回作成するアプリは、１週間で作成しなければならないのと、cssを自力で書ける人が少ない、そして祭りモード専用のデザインも作成しなければならないという３つの点から、tailwindcssを採用した方が良いと考える。
tailwindcssはフレームワークであり、決められたスタイルを用いてデザインを作成することができるため開発時間の短縮につながるのと、開発を補助するためのチートシートやUIコンポーネントがあり初学者でもすぐに扱いやすいという点からtailwindcssを勧める。

**Comment by molpui0726** [comment]
tailwind→レビューがしやすい

普段使わないユーティリティクラスや、ユーティリティがないCSSをブラケット付きで表現していると目立つ。使うと決めたクラスのみを用いることで、コードを読む段階である程度のデザインが想像できる。

**Comment by molpui0726** [comment]
cssはtailwindに決定

**Comment by molpui0726** [comment]
トップページから作成することに。
チームメンバーの環境構築が完了したため、トップページに配置するボタンを練習で作成する。
